package io.ticticboom.mods.tictec.materials.element;

import lombok.Getter;

public enum Element implements IElement {
    HYDROGEN("Hydrogen", "H", ElementCategory.NONMETALS, 0xFFFFFF),
    HELIUM("Helium", "He", ElementCategory.NOBLE_GASES, 0xd9ffff),
    LITHIUM("Lithium",  "Li", ElementCategory.ALKALI_METALS, 0xcc80ff),
    BERYLLIUM("Beryllium", "Be", ElementCategory.ALKALINE_EARTH_METALS, 0xc2ff00),
    BORON("Boron", "B", ElementCategory.METALLOIDS, 0xFFB5B5),
    CARBON("carbon", "C", ElementCategory.NONMETALS, 0x909090),
    NITROGEN("Nitrogen", "N", ElementCategory.NONMETALS, 0x3050F8),
    OXYGEN("Oxygen", "O", ElementCategory.NONMETALS, 0xFF0D0D),
    FLUORINE("Fluorine", "F", ElementCategory.HALOGENS, 0x90E050),
    NEON("Neon", "Ne", ElementCategory.NOBLE_GASES, 0xb3e3f5),
    SODIUM("Sodium", "Na", ElementCategory.ALKALI_METALS, 0xAB5cf2),
    MAGNESIUM("Magnesium", "Mg", ElementCategory.ALKALINE_EARTH_METALS, 0x8aff00),
    ALUMINIUM("Aluminium", "Al", ElementCategory.POST_TRANSITION_METALS, 0xbfa6a6),
    SILICON("Silicon", "Si", ElementCategory.METALLOIDS, 0xF0c8a0),
    PHOSPHORUS("Phosphorus", "P", ElementCategory.NONMETALS, 0xFF8000),
    SULFUR("Sulfur", "S", ElementCategory.NONMETALS, 0xFFFF30),
    CHLORINE("Chlorine", "Cl", ElementCategory.NONMETALS, 0x1FF01F),
    ARGON("Argon", "Ar", ElementCategory.NOBLE_GASES, 0x80D1E3),
    POTASSIUM("Potassium", "K", ElementCategory.ALKALI_METALS, 0x8f40D4),
    CALCIUM("Calcium", "Ca", ElementCategory.TRANSITION_METALS, 0x3DFF00),
    SCANDIUM("Scandium", "Sc", ElementCategory.TRANSITION_METALS, 0xE6E6E6),
    TITANIUM("Titanium", "Ti", ElementCategory.TRANSITION_METALS, 0xBFC2C7),
    VANADIUM("Vanadium", "V", ElementCategory.TRANSITION_METALS, 0xA6A6AB),
    CHROMIUM("Chromium", "Cr", ElementCategory.TRANSITION_METALS, 0x8A99C7),
    MANGANESE("Manganese", "Mn", ElementCategory.TRANSITION_METALS, 0x9C7AC7),
    IRON("Iron", "Fe", ElementCategory.TRANSITION_METALS, 0xFFFFFF),
    COBALT("Cobalt", "Co", ElementCategory.TRANSITION_METALS, 0x006985),
    NICKEL("Nickel", "Ni", ElementCategory.TRANSITION_METALS, 0x50D050),
    COPPER("Copper", "Cu", ElementCategory.TRANSITION_METALS, 0xC88033),
    ZINC("Zinc", "Zn", ElementCategory.TRANSITION_METALS, 0x7D80B0),
    GALLIUM("Gallium", "Ga", ElementCategory.POST_TRANSITION_METALS, 0xC28F8F),
    GERMANIUM("Germanium", "Ge", ElementCategory.METALLOIDS, 0x668f8f),
    ARSENIC("Arsenic", "As", ElementCategory.METALLOIDS, 0xBD80e3),
    SELENIUM("Selenium", "Se", ElementCategory.NONMETALS, 0xFFA100),
    BROMINE("Bromine", "Br", ElementCategory.HALOGENS, 0xA62929),
    KRYPTON("Krypton", "Kr", ElementCategory.NOBLE_GASES, 0x5CB8D1),
    RUBIDIUM("Rubidium", "Rb", ElementCategory.ALKALI_METALS, 0x702EB0),
    STRONTIUM("Strontium", "Sr", ElementCategory.ALKALINE_EARTH_METALS, 0x00FF00),
    YTTRIUM("Yttrium", "Y", ElementCategory.TRANSITION_METALS, 0x94FFFF),
    ZIRCONIUM("Zirconium", "Zr", ElementCategory.TRANSITION_METALS, 0x94E0E0),
    NIOBIUM("Niobium", "Nb", ElementCategory.TRANSITION_METALS, 0x73C2C9),
    MOLYBDENUM("Molybdenum", "Mo", ElementCategory.TRANSITION_METALS, 0x54B5B5),
    TECHNETIUM("Technetium", "Tc", ElementCategory.TRANSITION_METALS, 0x3B9E9E),
    RUTHENIUM("Ruthenium", "Ru", ElementCategory.TRANSITION_METALS, 0x248F8F),
    RHODIUM("Rhodium", "Rh", ElementCategory.TRANSITION_METALS, 0x0A7D8C),
    PALLADIUM("Palladium", "Pd", ElementCategory.TRANSITION_METALS, 0x006985),
    SILVER("Silver", "Ag", ElementCategory.TRANSITION_METALS, 0xC0C0C0),
    CADMIUM("Cadmium", "Cd", ElementCategory.TRANSITION_METALS, 0xFFD98F),
    INDIUM("Indium", "In", ElementCategory.POST_TRANSITION_METALS, 0xA67573),
    TIN("Tin", "Sn", ElementCategory.POST_TRANSITION_METALS, 0x668080),
    ANTIMONY("Antimony", "Sb", ElementCategory.METALLOIDS, 0x9E63B5),
    TELLURIUM("Tellurium", "Te", ElementCategory.METALLOIDS, 0xD47A00),
    IODINE("Iodine", "I", ElementCategory.HALOGENS, 0x940094),
    XEON("Xeon", "Xe", ElementCategory.NOBLE_GASES, 0x429EB0),
    CESIUM("Cesium", "Cs", ElementCategory.ALKALI_METALS, 0x57178F),
    BARIUM("Barium", "Ba", ElementCategory.ALKALINE_EARTH_METALS, 0x00C900),
    LANTHANUM("Lanthanum", "La", ElementCategory.LANTHANIDES, 0x70D4FF),
    CERIUM("Cerium", "Ce", ElementCategory.LANTHANIDES, 0xFFFFC7),
    PRASEODYMIUM("Praseodymium", "Pr", ElementCategory.LANTHANIDES, 0xD9FFC7),
    NEODYMIUM("Neodymium", "Nd", ElementCategory.LANTHANIDES, 0xC7FFC7),
    PROMETHIUM("Promethium", "Pm", ElementCategory.LANTHANIDES, 0xA3FFC7),
    SAMARIUM("Samarium", "Sm", ElementCategory.LANTHANIDES, 0x8FFFC7),
    EUROPIUM("Europium", "Eu", ElementCategory.LANTHANIDES, 0x61FFC7),
    GADOLINIUM("Gadolinium", "Gd", ElementCategory.LANTHANIDES, 0x45FFC7),
    TERBIUM("Terbium", "Tb", ElementCategory.LANTHANIDES, 0x30FFC7),
    DYSPROSIUM("Dysprosium", "Dy", ElementCategory.LANTHANIDES, 0x1FFFC7),
    HOLMIUM("Holmium", "Ho", ElementCategory.LANTHANIDES, 0x00FF9C),
    ERBIUM("Erbium", "Er", ElementCategory.LANTHANIDES, 0x00E675),
    THULIUM("Thulium", "Tm", ElementCategory.LANTHANIDES, 0x00D452),
    YTTERBIUM("Ytterbium", "Yb", ElementCategory.LANTHANIDES, 0x00BF38),
    LUTETIUM("Lutetium", "Lu", ElementCategory.LANTHANIDES, 0x00AB24),
    HAFNIUM("Hafnium", "Hf", ElementCategory.TRANSITION_METALS, 0x4DC2FF),
    TANTALUM("Tantalum", "Ta", ElementCategory.TRANSITION_METALS, 0x4DA6FF),
    TUNGSTEN("Tungsten", "W", ElementCategory.TRANSITION_METALS, 0x2194D6),
    RHENIUM("Rhenium", "Re", ElementCategory.TRANSITION_METALS, 0x267DAB),
    OSMIUM("Osmium", "Os", ElementCategory.TRANSITION_METALS, 0x266696),
    IRIDIUM("Iridium", "Ir", ElementCategory.TRANSITION_METALS, 0x175487),
    PLATINUM("Platinum", "Pt", ElementCategory.TRANSITION_METALS, 0xD0D0E0),
    GOLD("Gold", "Au", ElementCategory.TRANSITION_METALS, 0xFFD123),
    MERCURY("Mercury", "Hg", ElementCategory.TRANSITION_METALS, 0xB8B8D0),
    THALLIUM("Thallium", "Tl", ElementCategory.POST_TRANSITION_METALS, 0xA6544D),
    LEAD("Lead", "Pb", ElementCategory.POST_TRANSITION_METALS, 0x575961),
    BISMUTH("Bismuth", "Bi", ElementCategory.POST_TRANSITION_METALS, 0x9E4FB5),
    POLONIUM("Polonium", "Po", ElementCategory.METALLOIDS, 0xAB5C00),
    ASTATINE("Astatine", "At", ElementCategory.HALOGENS, 0x754F45),
    RADON("Radon", "Rn", ElementCategory.NOBLE_GASES, 0x428296),
    FRANCIUM("Francium", "Fr", ElementCategory.ALKALI_METALS, 0x420066),
    RADIUM("Radium", "Ra", ElementCategory.ALKALINE_EARTH_METALS, 0x007D00),
    ACTINIUM("Actinium", "Ac", ElementCategory.ACTINIDES, 0x70ABFA),
    THORIUM("Thorium", "Th", ElementCategory.ACTINIDES, 0x00BAFF),
    PROTACTINIUM("Protactinium", "Pa", ElementCategory.ACTINIDES, 0x00A1FF),
    URANIUM("Uranium", "U", ElementCategory.ACTINIDES, 0x008FFF),
    NEPTUNIUM("Neptunium", "Np", ElementCategory.ACTINIDES, 0x0080FF),
    PLUTONIUM("Plutonium", "Pu", ElementCategory.ACTINIDES, 0x006BFF),
    AMERICIUM("Americium", "Am", ElementCategory.ACTINIDES, 0x545CF2),
    CURIUM("Curium", "Cm", ElementCategory.ACTINIDES, 0x785CE3),
    BERKELIUM("Berkelium", "Bk", ElementCategory.ACTINIDES, 0x8A4FE3),
    CALIFORNIUM("Californium", "Cf", ElementCategory.ACTINIDES, 0xA136D4),
    EINSTEINIUM("Einsteinium", "Es", ElementCategory.ACTINIDES, 0xB31FD4),
    FERMIUM("Fermium", "Fm", ElementCategory.ACTINIDES, 0xB31FBA),
    MENDELEVIUM("Mendelevium", "Md", ElementCategory.ACTINIDES, 0xB30DA6),
    NOBELIUM("Nobelium", "No", ElementCategory.ACTINIDES, 0xBD0D87),
    LAWRENCIUM("Lawrencium", "Lr", ElementCategory.ACTINIDES, 0xC70066),
    RUTHERFORDIUM("Rutherfordium", "Rf", ElementCategory.TRANSITION_METALS, 0xCC0059),
    DUBNIUM("Dubnium", "Db", ElementCategory.TRANSITION_METALS, 0xD1004F),
    SEABORGIUM("Seaborgium", "Sg", ElementCategory.TRANSITION_METALS, 0xD90045),
    BOHRIUM("Bohrium", "Bh", ElementCategory.TRANSITION_METALS, 0xE00038),
    HASSIUM("Hassium", "Hs", ElementCategory.TRANSITION_METALS, 0xE6002E),
    MEITNERIUM("Meitnerium", "Mt", ElementCategory.TRANSITION_METALS, 0xEB0026),
    DARMSTADTIUM("Darmstadtium", "Ds", ElementCategory.TRANSITION_METALS, 0xFFFFFF),
    ROENTGENIUM("Roentgenium", "Rg", ElementCategory.TRANSITION_METALS, 0xFFFFFF),
    COPERNICIUM("Copernicium", "Cn", ElementCategory.TRANSITION_METALS, 0xFFFFFF),
    NIHONIUM("Nihonium", "Nh", ElementCategory.POST_TRANSITION_METALS, 0xFFFFFF),
    FLEROVIUM("Flerovium", "Sg", ElementCategory.POST_TRANSITION_METALS, 0xFFFFFF),
    MOSCOVIUM("Moscovium", "Sg", ElementCategory.POST_TRANSITION_METALS, 0xFFFFFF),
    LIVERMORIUM("Livermorium", "Sg", ElementCategory.POST_TRANSITION_METALS, 0xFFFFFF),
    TENNESSINE("Tennessine", "Sg", ElementCategory.HALOGENS, 0xFFFFFF),
    OGANESSON("Oganesson", "Sg", ElementCategory.NOBLE_GASES, 0xFFFFFF),

    ;
    @Getter
    private final String name;
    @Getter
    private final String symbol;
    @Getter
    private final ElementCategory category;
    @Getter
    private int color;

    Element(String name, String symbol, ElementCategory category, int color) {
        this.name = name;
        this.symbol = symbol;
        this.category = category;
        this.color = color;
    }
}
